#pragma once
// 场景面板

// 场景header
#define SCENE_TAB_HEADER_TITLE StringHelper::fetch("SCENE_TAB_HEADER_TITLE")

// 场景中物体的名字
#define SCENE_TAB_OBJECT_TITLE StringHelper::fetch("SCENE_TAB_OBJECT_TITLE")

// 场景中灯光的名字
#define SCENE_TAB_LIGHT_TITLE_0 StringHelper::fetch("SCENE_TAB_LIGHT_TITLE_0")
#define SCENE_TAB_LIGHT_TITLE_1 StringHelper::fetch("SCENE_TAB_LIGHT_TITLE_1")
#define SCENE_TAB_LIGHT_TITLE_2 StringHelper::fetch("SCENE_TAB_LIGHT_TITLE_2")
#define SCENE_TAB_LIGHT_TITLE_3 StringHelper::fetch("SCENE_TAB_LIGHT_TITLE_3")

// 环境面板

// header
#define ENV_TAB_ENV_ARGS_HEADER_TITLE StringHelper::fetch("ENV_TAB_ENV_ARGS_HEADER_TITLE")

// 参数
#define ENV_TAB_ARG_RH StringHelper::fetch("ENV_TAB_ARG_RH")
#define ENV_TAB_ARG_CC StringHelper::fetch("ENV_TAB_ARG_CC")
#define ENV_TAB_ARG_SC StringHelper::fetch("ENV_TAB_ARG_SC")
#define ENV_TAB_ARG_OC StringHelper::fetch("ENV_TAB_ARG_OC")
#define ENV_TAB_ARG_TEMPERATURE StringHelper::fetch("ENV_TAB_ARG_TEMPERATURE")
#define ENV_TAB_ARG_ROUGHNESS StringHelper::fetch("ENV_TAB_ARG_ROUGHNESS")
#define ENV_TAB_ARG_METALLIC StringHelper::fetch("ENV_TAB_ARG_METALLIC")
#define ENV_TAB_ARG_CONCENTRATION StringHelper::fetch("ENV_TAB_ARG_CONCENTRATION")
#define ENV_TAB_ARG_MODEL_SURFACE StringHelper::fetch("ENV_TAB_ARG_MODEL_SURFACE")

// 物体检视面板 0x02

// header
#define OBJECT_TAB_OBJECT_HEADER_TITLE StringHelper::fetch("OBJECT_TAB_OBJECT_HEADER_TITLE")
#define OBJECT_TAB_LIGHT_HEADER_TITLE StringHelper::fetch("OBJECT_TAB_LIGHT_HEADER_TITLE")

// 模型路径tag
#define OBJECT_TAB_OBJECT_MODEL_PATH StringHelper::fetch("OBJECT_TAB_OBJECT_MODEL_PATH")
#define OBJECT_TAB_SELECT_MODEL StringHelper::fetch("OBJECT_TAB_SELECT_MODEL")

// 位置
#define OBJECT_TAB_LOC StringHelper::fetch("OBJECT_TAB_LOC")

#define OBJECT_TAB_LOC_X StringHelper::fetch("OBJECT_TAB_LOC_X")
#define OBJECT_TAB_LOC_Y StringHelper::fetch("OBJECT_TAB_LOC_Y")
#define OBJECT_TAB_LOC_Z StringHelper::fetch("OBJECT_TAB_LOC_Z")

#define OBJECT_TAB_ROT StringHelper::fetch("OBJECT_TAB_ROT")
#define OBJECT_TAB_ROT_X StringHelper::fetch("OBJECT_TAB_ROT_X")
#define OBJECT_TAB_ROT_Y StringHelper::fetch("OBJECT_TAB_ROT_Y")
#define OBJECT_TAB_ROT_Z StringHelper::fetch("OBJECT_TAB_ROT_Z")

#define OBJECT_TAB_SCL StringHelper::fetch("OBJECT_TAB_SCL")
#define OBJECT_TAB_SCL_X StringHelper::fetch("OBJECT_TAB_SCL_X")
#define OBJECT_TAB_SCL_Y StringHelper::fetch("OBJECT_TAB_SCL_Y")
#define OBJECT_TAB_SCL_Z StringHelper::fetch("OBJECT_TAB_SCL_Z")

#define OBJECT_TAB_LIGHT_INTENSITY StringHelper::fetch("OBJECT_TAB_LIGHT_INTENSITY")

// 节点面板

// 添加节点面板
#define LAYER_TAB_TITLE StringHelper::fetch("LAYER_TAB_TITLE")

#define NODE_EDITOR_PANEL_CUSTOM_LAYER StringHelper::fetch("NODE_EDITOR_PANEL_CUSTOM_LAYER")
#define NODE_EDITOR_PANEL_PERLIN_LAYER StringHelper::fetch("NODE_EDITOR_PANEL_PERLIN_LAYER")
#define NODE_EDITOR_PANEL_DPD_LAYER StringHelper::fetch("NODE_EDITOR_PANEL_DPD_LAYER")
#define NODE_EDITOR_PANEL_LAYER_MACHINE StringHelper::fetch("NODE_EDITOR_PANEL_LAYER_MACHINE")
#define NODE_EDITOR_PANEL_SAVE_CONFIG StringHelper::fetch("NODE_EDITOR_PANEL_SAVE_CONFIG")
#define NODE_EDITOR_PANEL_READ_CONFIG StringHelper::fetch("NODE_EDITOR_PANEL_READ_CONFIG")

#define NODE_EDITOR_NODE_WIDGET_ENTRY_COLOR StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_COLOR")
#define NODE_EDITOR_NODE_WIDGET_ENTRY_TRANSMITTANCE StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_TRANSMITTANCE")
#define NODE_EDITOR_NODE_WIDGET_ENTRY_ROUGHNESS StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_ROUGHNESS")
#define NODE_EDITOR_NODE_WIDGET_ENTRY_METALLIC StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_METALLIC")
#define NODE_EDITOR_NODE_WIDGET_ENTRY_DPD_RANDOMIZER StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_DPD_RANDOMIZER")
#define NODE_EDITOR_NODE_WIDGET_ENTRY_DIFFUSE_SPD StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_DIFFUSE_SPD")


#define NODE_EDITOR_NODE_WIDGET_ENTRY_BIAS_HEIGHT StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_BIAS_HEIGHT")
#define NODE_EDITOR_NODE_WIDGET_ENTRY_CUTOFF_HEIGHT StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_CUTOFF_HEIGHT")
#define NODE_EDITOR_NODE_WIDGET_ENTRY_BLOCK_WIDTH StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_BLOCK_WIDTH")

#define NODE_EDITOR_NODE_WIDGET_ENTRY_NAME StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_NAME")
#define NODE_EDITOR_NODE_WIDGET_ENTRY_DEFAULT_NAME StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_DEFAULT_NAME")

#define NODE_EDITOR_NODE_WIDGET_ENTRY_CONFIG StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_CONFIG")

#define NODE_EDITOR_NODE_WIDGET_ENTRY_PART_PER_SEC StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_PART_PER_SEC")
#define NODE_EDITOR_NODE_WIDGET_ENTRY_DEFAULT_PART_PER_SEC StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_DEFAULT_PART_PER_SEC")

#define NODE_EDITOR_NODE_WIDGET_ENTRY_GROW_SPD StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_GROW_SPD")
#define NODE_EDITOR_NODE_WIDGET_ENTRY_DEFAULT_GROW_SPD StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_DEFAULT_GROW_SPD")
#define NODE_EDITOR_NODE_WIDGET_ENTRY_INIT_SEED StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_INIT_SEED")

#define NODE_EDITOR_NODE_WIDGET_ENTRY_LAYER_0 StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_LAYER_0")
#define NODE_EDITOR_NODE_WIDGET_ENTRY_LAYER_1 StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_LAYER_1")
#define NODE_EDITOR_NODE_WIDGET_ENTRY_LAYER_2 StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_LAYER_2")
#define NODE_EDITOR_NODE_WIDGET_ENTRY_LAYER_3 StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_LAYER_3")
#define NODE_EDITOR_NODE_WIDGET_ENTRY_LAYER_4 StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_LAYER_4")

#define NODE_EDITOR_NODE_WIDGET_ENTRY_EMPTY_SLOT StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_ENTRY_EMPTY_SLOT")

#define NODE_EDITOR_NODE_WIDGET_PERLIN_LAYER_TITLE StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_PERLIN_LAYER_TITLE")
#define NODE_EDITOR_NODE_WIDGET_DPD_LAYER_TITLE StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_DPD_LAYER_TITLE")
#define NODE_EDITOR_NODE_WIDGET_LAYER_MACHINE_TITLE StringHelper::fetch("NODE_EDITOR_NODE_WIDGET_LAYER_MACHINE_TITLE")

#define HEADER_LOAD_ARCHIVE StringHelper::fetch("HEADER_LOAD_ARCHIVE")
#define HEADER_SAVE_ARCHIVE StringHelper::fetch("HEADER_SAVE_ARCHIVE")
#define HEADER_SAVE_OUTPUT StringHelper::fetch("HEADER_SAVE_OUTPUT")

#define BAKE_TAB_HEADER StringHelper::fetch("BAKE_TAB_HEADER")
#define BAKE_TAB_USE_DISTURB StringHelper::fetch("BAKE_TAB_USE_DISTURB")
#define BAKE_TAB_DISTURB_FACTOR StringHelper::fetch("BAKE_TAB_DISTURB_FACTOR")
#define BAKE_TAB_USE_DEPTH StringHelper::fetch("BAKE_TAB_USE_DEPTH")
#define BAKE_TAB_TIME StringHelper::fetch("BAKE_TAB_TIME")
#define BAKE_TAB_ILLUSION StringHelper::fetch("BAKE_TAB_ILLUSION")
#define BAKE_TAB_NOISE StringHelper::fetch("BAKE_TAB_NOISE")
#define BAKE_TAB_WAVE_LENGTH StringHelper::fetch("BAKE_TAB_WAVE_LENGTH")
#define BAKE_TAB_REGENERATE_NOISE StringHelper::fetch("BAKE_TAB_REGENERATE_NOISE")

#define IMG_DRAWER_SWITCH_VIEW_MODE StringHelper::fetch("IMG_DRAWER_SWITCH_VIEW_MODE")
#define IMG_DRAWER_PREVIEW StringHelper::fetch("IMG_DRAWER_PREVIEW")

#define OUTPUT_TAB_SAVE StringHelper::fetch("OUTPUT_TAB_SAVE")
#define OUTPUT_TAB_HEADER StringHelper::fetch("OUTPUT_TAB_HEADER")
#define OUTPUT_TAB_DIFFUSE StringHelper::fetch("OUTPUT_TAB_DIFFUSE")
#define OUTPUT_TAB_ROUGHNESS StringHelper::fetch("OUTPUT_TAB_ROUGHNESS")
#define OUTPUT_TAB_METALLIC StringHelper::fetch("OUTPUT_TAB_METALLIC")
#define OUTPUT_TAB_HEIGHT StringHelper::fetch("OUTPUT_TAB_HEIGHT")
#define OUTPUT_TAB_NORMAL_DISTURB StringHelper::fetch("OUTPUT_TAB_NORMAL_DISTURB")

#define PLAYER_TITLE StringHelper::fetch("PLAYER_TITLE")

#define APPLICATION_TITLE StringHelper::fetch("APPLICATION_TITLE")
